### ISSUE TITLE
Question 3.7 still remains unanswered

### ISSUE THREAD

**Issue by SuyashD95** [SuyashD95/cplusplus-prog-exercises#23]
Have some difficulty in understanding the problem statement of this question... Hence, will focus once I have finished the remaining questions of chapter 3.

**Comment by SuyashD95** [comment]
**Update 1**: Created three branches '_prog-ex-3.7-a_', '_prog-ex-3.7-b_' and '_prog-ex-3.7-c_' to track the progress of each part of this question.

**Comment by SuyashD95** [comment]
I am going to start working on finding the solution to the second part of this question...

**Comment by SuyashD95** [comment]
**Tasks TO-DO (1)** for completing the solution to the **_(b)_** part of the question:

- [x] Include _cmath_ header file to use the pow() function. (Completed in _Update 2_)
- [x] Create a function for each individual term of the form (1/n)^n. (Completed in _Update 2_)
- [x] Create a '_for_' loop to calculate the SUM of the series consisting of n-terms (n will be user-defined). (Completed in _Update 2_)

**Comment by SuyashD95** [comment]
**Update 2**: The answer to the **(b)**  part of the question is complete.

**Tasks Completed** in this update:

- Include cmath header file to use the pow() function.
- Create a function to each individual term of the form (1/n)^n.
- Create a 'for' loop to calculate the SUM of the series consisting of n-terms (n will be user-defined).

**P.S:** Branch '_prog-ex-3.7-b'_ will be deleted after it is merged with its base branch '_prog-ex-3.7_'

**Comment by SuyashD95** [comment]
Started working on the first part of this question... _'Prog-ex-3.7-a'_ will be the working branch...

**Comment by SuyashD95** [comment]
**Tasks TO-DO (2)** for completing the solution to the **(a)** part of the question:
- [x]  Include cmath header file to use the required mathematical functions and constants. (Completed in _Update 3_)
- [x]  Define a function to convert degrees to radians. (Completed in _Update 3_)
- [x]  Find the true or correct value of the function: sin x.(where x is in radians). (Completed in _Update 3_)
- [x]  Declare the fundamental variables to be used in the calculating the approximate value. (Completed in 
      _Update 4_)
- [x]  Define a factorial function as a helper function to calculate the term. (Completed in _Update 5_)
- [x]  Calculate the value of each individual term. (Completed in _Update 5_)
- [x]  Check whether a particular term is positive or negative in nature to satisfy the alternating nature of 
        the series. (Completed in _Update 6_)
- [x]  Check whether a particular term is included in the calculation (greater or equal to the accuracy limit) 
        and use it as the condition to come out _(break)_ of the infinite '_while(true)_' loop. (Completed in 
        _Update 5_)
- [x]  Test the correctness of the answer by finding out the absolute difference between trueSine and 
        apparentSine values. (Completed in _Update 6_)

**Comment by SuyashD95** [comment]
**Update 3**: Completed 3 tasks related to answering **(a)** of the question:

_**Task(s) Completed:**_

-  Include cmath header file to use the required mathematical functions and constants.
-  Define a function to convert degrees to radians.
-  Find the true or correct value of the function: sin x (where x is in radians).

_Info about the functions defined in this update:_

1. **degToRad:** Defined an inline function to convert degrees to radians for calculation purposes.

**Comment by SuyashD95** [comment]
**IMPORTANT NOTE:** After digging a little deeper into the question and researching, I have found the core mathematical concept on which the logic of the solution heavily depends...

_Core Concept used as the basis for the question:_

- _**Calculating an approximate value of a transcendental function with accuracy using power series expansions**_

I might add a PDF later on to explain and elaborate on this concepts for your ease and making you understand the solution better...

But, _this is not confirmed and I might decide not to upload the PDF if I found myself too pressed for time.._ 

So, please do research a bit about this topic and concept... This is really important since I will be using this concept as the most fundamental building block of the solution. Otherwise, there is a possibility that you might not be able to understand the solution of any of the given parts.

**Comment by SuyashD95** [comment]
**Update 4**: Completed a task related to answering part **(a)** of the question:

_**Task(s) Completed:**_

- Declare the fundamental variables to be used in the calculating the approximate value.

**Comment by SuyashD95** [comment]
**Update 5**: The following 3 tasks have been completed in this update...

_**Task(s) Completed:**_

-  Define a factorial function as a helper function to calculate the term. 
-  Calculate the value of each individual term. 
-  Check whether a particular term is included in the calculation (greater or equal to the accuracy limit) and use it as the condition to come out (break) of the infinite 'while(true)' loop.

_Info regarding the changes happened in this update:_

1. **factorial**: Defined a function to calculate the factorial of the given positive number using recursion.
2. **Fundamental structure of the _'while(true)'_ loop is completed**
    -  _Calculate each term depending on the value of the exponent._
    -  _Conditional statement to exit from the infinite 'while(true)' loop, when a term is less than accuracy i.e, 0.0001._
    -  _Increment the power by 2._

**Comment by SuyashD95** [comment]
**Update 6**: The answer to the **(a)**  part of the question is complete.

**Task(s) Completed** in this update:

- Check whether a particular term is positive or negative in nature to satisfy the alternating nature of the 
  series. 
-  Test the correctness of the answer by finding out the absolute difference between trueSine and 
   apparentSine values.

**P.S:** Branch '_prog-ex-3.7-a'_ will be deleted after it is merged with its base branch '_prog-ex-3.7_'

**Comment by SuyashD95** [comment]
Will start working on the last remaining part (c) of the question...

**Comment by SuyashD95** [comment]
**Tasks TO-DO (3)** for completing the solution to the **(c)** part of the question:

- [x] Modify the solution of the first part (a) for this answer. Same principles and general logic for the solution remains the same, the only difference is instead of calculating the sine value, we are calculating the cosine value. (Updated in _Update 7_)

**Comment by SuyashD95** [comment]
**Update 7**: The answer to the **(c)**  part is completed.

**Task(s) Completed** in this update:

- Modify the solution of the first part (a) for this answer. Same principles and general logic for the solution remains the same, the only difference is instead of calculating the sine value, we are calculating the cosine value. 

**P.S:** Branch '_prog-ex-3'_ will be deleted after it is merged with its base branch 'master'
