### ISSUE TITLE
Question 3.9 still remains unanswered

### ISSUE THREAD

**Issue by SuyashD95** [SuyashD95/cplusplus-prog-exercises#25]

**Comment by SuyashD95** [comment]
**Update 1**: Switch to branch '_prog-ex-3.9-solution_' to track the progress of the answer.

**Comment by SuyashD95** [comment]
**TO-DO LIST**

- [x] Include _cmath_ header file to use the sqrt() and pow() functions. (Completed in _Update 2_)
- [x] Ask user to populate a data-set consisting of N numbers (N is also user-defined). (Completed in _Update 2_)
- [x] Define a function to find the _Mean_ of N numbers.
- [x] Define a function to calculate the _Variance_ of N numbers.
- [x] Define a function to calculate the _Standard Deviation_ of N numbers.

(Formulas used for calculating Mean, Variance and Standard Deviation are mentioned in the problem statement)

**Comment by SuyashD95** [comment]
**Update 2**: Completed the first 2 tasks related to completing the solution to this answer...

_**Task(s) Completed:**_

-  Include cmath header file to use the sqrt() and pow() functions.
-  Ask user to populate a data-set consisting of N numbers (N is also user-defined).

_Info about the functions defined_ in this update:

1. **findN**: Added this function to find the size of the data and return an integer which could be then, used as a constant. 

2. **insertSuffix**: Function used to insert a suffix (-st, -nd, -rd & -th) to the numerical value... Used as a helper function for another function, _populateData_.

3. **populateData**: This function is a primary one since, it's responsibility is to populate the data-set of N numbers.

**Comment by SuyashD95** [comment]
**Update 3**: Complete a task mentioned in the _TO-DO LIST_..

_**Task(s) Completed:**_

- Define a function to find the Mean of N numbers.

_Info about the functions defined_ in this update:

1. **calculateMean**: This function calculates the Mean of data consisting of N numbers.

**Comment by SuyashD95** [comment]
**Update 4**: The solution to question 9 of Chapter 3 is complete.

_**Task(s) Completed:**_

-  Define a function to calculate the Variance of N numbers.
-  Define a function to calculate the Standard Deviation of N numbers.

_Info about the functions defined_  in this update:

1. **calculateVariance**: This function calculates the Variance of data consisting of N numbers.

2. **calculateStandardDeviation**: This function calculates the Standard Deviation of data consisting of N numbers.

And, hence, with this update, this issue is now _**closed**_.

**P.S:** Branches '_prog-ex-3.9-solution_' and '_prog-ex-3.9_' will be _deleted after it is merged_ with its base branches.
