### ISSUE TITLE
Attempting to find a solution to Question 8 of Chapter 4

### ISSUE THREAD

**Issue by SuyashD95** [SuyashD95/cplusplus-prog-exercises#32]

**Comment by SuyashD95** [comment]
**TO-DO LIST**
- [x] Declare and define a function which takes a **double** (for **m**) and an **integer** (for **n**) as parameters and calculate the power of m when raised to n... Since, this function is same as the one done in question 4.7, we can safely reuse it (as mentioned in the problem statement). (Completed in _Update 1_)
- [x] Define and declare another function which performs the same functionality except takes an **integer** value for **m**. (Completed in _Update 1_)
- [x] Write a **main()** that calls both the functions to show the concept of function overloading. (Completed in _Update 1_)

**NOTE:** It is _**highly recommended**_ to all the people who are attempting this question to first solve and understand the question 4.7, since this question is a follow-up to the aforementioned question.. And, there might be slight possibility that you might find this problem especially, the code of the **power()** function...

If you find yourself struggling, please check out answer of Question 7 of Chapter 4 (or even issue #31).

**Comment by SuyashD95** [comment]
**Update 1**: Due to the simplicity of the answer, I have directly committed the complete solution to branch '_prog-ex-4_'.

_**Task(s) Completed:**_

- Declare and define a function which takes a double (for m) and an integer (for n) as parameters and 
  calculate the power of m when raised to n... Since, this function is same as the one done in question 
  4.7, we can safely reuse it (as mentioned in the problem statement).
-  Define and declare another function which performs the same functionality except takes an integer 
   value for m.
-  Write a main() that calls both the functions to show the concept of function overloading.

And, thus, this issue is now _'**closed**_'.
