### ISSUE TITLE
Attempting to find a solution to Question 9 of Chapter 4

### ISSUE THREAD

**Issue by SuyashD95** [SuyashD95/cplusplus-prog-exercises#33]

**Comment by SuyashD95** [comment]
**TO-DO LIST** to complete this solution:
- [x] Define a macro for the value of Pi. (Completed in _Update 1_)
- [x] Create an area() function to calculate the area of a triangle. (Completed in _Update 3_)
- [x] Create a second area() function to calculate the area of a circle. (Completed in _Update 3_)
- [x] Exhibit function overloading of the area() function. (Completed in _Update 2_)

**Comment by SuyashD95** [comment]
**Update 1**: Created a branch '_prog-ex-4.9-solution_' to track the progress of this solution.

In this update, I have committed the initial template of this solution.

**_Task(s) Completed:_**

- Define a macro for the value of Pi.

**Comment by SuyashD95** [comment]
**Update 2**: In this update, I have added the fundamental building blocks of the solution..

_**Task(s) Completed:**_

- Exhibit function overloading of the area() function.

While I can exhibit the overloading of the area() function, but this answer is not yet complete since I have added **stubs** in the aforementioned function to test the program..

Hence, this program _still doesn't calculate the area of the shapes_ (circle & triangle) and will be added in the next update.

**Comment by SuyashD95** [comment]
**Update 3**: The answer of this question is complete and hence, with this update, this issue is now _**'closed'**_.

_**Task(s) Completed:**_
-  Create an area() function to calculate the area of a triangle.
-  Create a second area() function to calculate the area of a circle.

**P.S:** Branch _'prog-ex-4.9-solution'_ will be **deleted** after it has merged with its base branch, since it has served its purpose.
