### ISSUE TITLE
Question 4.4 still remains unanswered

### ISSUE THREAD

**Issue by SuyashD95** [SuyashD95/cplusplus-prog-exercises#35]

**Comment by SuyashD95** [comment]
**TO-DO LIST** to complete this solution:

- [x] Define a macro ROW_COUNT to store the number of rows, in case of overloaded functions.
 (Completed in _Update 1_)

- [x] Overload and make necessary modifications to all the functions (already defined in question 4.3).
 (Completed in _Update 1_)

- [x] Use _main_ function as a platform to test and showcase the concept of function overloading.
 (Completed in _Update 1_)

**Comment by SuyashD95** [comment]
**Update 1**: Due to the simplicity of the answer, I have directly committed the complete solution to branch '_prog-ex-4_'

_**Task(s) Completed**_:

-  Define a macro ROW_COUNT to store the number of rows, in case of overloaded functions.
-  Overload and make necessary modifications to all the functions (already defined in question 4.3).
-  Use main function as a platform to test and showcase the concept of function overloading.

_Names of all the functions that have been overloaded:_
1. **allocateMemory**
2. **deallocateMemory**
3. **readMatrix**
4. **displayMatrix**

Thus, this issue is now considered _**closed**_.

**NOTE TO READERS:** Since the complete code has been written in a single .cpp file, therefore, the number of lines of code is relatively larger than any of the earlier solutions...

But, in reality, only a few lines of code have been added/modified... And, they can easily be observed and noticed if you have completed the previous two questions (4.2 & 4.3)..

So, _**it is highly recommended**_ to solve the aforementioned questions before attempting this question.
