### ISSUE TITLE
Question 5.5 still remains unanswered

### ISSUE THREAD

**Issue by SuyashD95** [SuyashD95/cplusplus-prog-exercises#46]

**Comment by SuyashD95** [comment]
**TO-DO**

- [x] Create a header and a source file for class _DB_. (Completed in _Update 1_)
- [x] Create a header and a source file for class _DM_. (Completed in _Update 2_)
- [x] Define a friend function _addDistance_ to add the distance of the two objects (one in DB and other in 
      DM) and display the result depending on the choice of the user. (Completed in _Update 3_)

**Comment by SuyashD95** [comment]
**Update 1**:

_**Task(s) Completed:**_

- Create a header and a source file for class DB. (Completed in Update 1)

**Comment by SuyashD95** [comment]
**Update 2**:

_**Task(s) Completed:**_

- Create a header and a source file for class DM.

**Comment by SuyashD95** [comment]
**Update 3**:

_**Task(s) Completed:**_

- Define a friend function _addDistance_ to add the distance of the two objects (one in DB and other in         
  DM) and display the result depending on the choice of the user.

**P.S:** The answer to this question is complete and hence, this issue is now **_closed_**.
